apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: solr
    name: solr
  spec:
    ports:
    - name: "8983"
      port: 8983
      targetPort: 8983
    selector:
      io.kompose.service: solr
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: solr
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: solr
      spec:
        containers:
        - image: bitnami/solr:latest
          name: solr
          ports:
          - containerPort: 8983
          resources: {}
          volumeMounts:
          - mountPath: /bitnami/solr
            name: solr-solr-data
        restartPolicy: Always
        volumes:
        - name: solr-solr-data
          persistentVolumeClaim:
            claimName: solr-solr-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: solr-solr-data
    name: solr-solr-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
kind: List
metadata: {}

